apply plugin: 'maven-publish'

// 从 local.properties 读取 Maven 凭证
def mavenUsername = project.findProperty("maven_username") ?: System.getenv("ALIYUN_USERNAME")
def mavenPassword = project.findProperty("maven_password") ?: System.getenv("ALIYUN_PASSWORD")

afterEvaluate {
    android.libraryVariants.all { variant ->
        variant.outputs.each { output ->
            def publicationName = variant.name.capitalize() + "Release"
            publishing.publications.create(publicationName, MavenPublication) {
                from components.findByName("android${publicationName}")
                groupId = GROUP
                artifactId = artifactId
                version = VERSION
            }
        }
    }

    publishing.repositories {
        maven {
            // 判断是 release 还是 snapshot
            def releasesRepoUrl = "https://packages.aliyun.com/maven/repository/2202395-release-jr0puW/"
            def snapshotsRepoUrl = "https://packages.aliyun.com/maven/repository/2202395-snapshot-3OoSzj/"

            url = VERSION.endsWith('SNAPSHOT') ? snapshotsRepoUrl : releasesRepoUrl
            credentials {
                username mavenUsername
                password mavenPassword
            }
        }
    }
}