buildscript {
    repositories {
        maven { url 'https://maven.aliyun.com/repository/public/' }
        maven { url 'https://maven.aliyun.com/repository/google' }
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.0"
    }
}

plugins {
    id 'java-library'
    id 'groovy'
    id 'kotlin'
    id 'maven-publish'
}

repositories {
    google()
    mavenCentral()
    maven { url 'https://maven.aliyun.com/repository/jcenter/' }
    maven { url 'https://maven.aliyun.com/repository/public/' }
    maven { url 'https://maven.aliyun.com/repository/google/' }

    maven {
        credentials {
            username "$ALIYUN_USERNAME"
            password "$ALIYUN_PASSWORD"
        }
        url 'https://packages.aliyun.com/maven/repository/2202395-release-jr0puW/'
    }
}

sourceCompatibility = 17

compileKotlin {
    kotlinOptions.jvmTarget = "17"
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    implementation(gradleApi())
    implementation(localGroovy())
    implementation('com.squareup:javapoet:1.13.0')
    api("com.android.tools.build:gradle:7.4.0")
    implementation("commons-io:commons-io:2.11.0")
    implementation("commons-codec:commons-codec:1.15")
    implementation("org.javassist:javassist:3.28.0-GA")
    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.8.0"
}

group = GROUP
version = VERSION

java {
    withSourcesJar()
    withJavadocJar()
}

// 从 local.properties 读取 Maven 凭证
def mavenUsername = project.findProperty("maven_username") ?: System.getenv("ALIYUN_USERNAME")
def mavenPassword = project.findProperty("maven_password") ?: System.getenv("ALIYUN_PASSWORD")

publishing {
    publications {
        maven(MavenPublication) {
            artifactId = 'okrouter-plugin'
            from components.java
        }
    }

    repositories {
        maven {
            // 判断是 release 还是 snapshot
            def releasesRepoUrl = "https://packages.aliyun.com/maven/repository/2202395-release-jr0puW/"
            def snapshotsRepoUrl = "https://packages.aliyun.com/maven/repository/2202395-snapshot-3OoSzj/"

            url = VERSION.endsWith('SNAPSHOT') ? snapshotsRepoUrl : releasesRepoUrl
            credentials {
                username mavenUsername
                password mavenPassword
            }
        }

    }
}
