buildscript {
    repositories {
        maven { url 'https://maven.aliyun.com/repository/public/' }
        maven { url 'https://maven.aliyun.com/repository/google' }
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.1.0"
    }
}

//plugins {
//    id 'org.jetbrains.kotlin.jvm' version '1.3.72'
//}
apply plugin: 'java-library'
apply plugin: 'groovy'
apply plugin: 'java'
apply plugin: 'kotlin'
apply plugin: 'maven-publish'


repositories {
    google()
    mavenCentral()
    maven { url 'https://maven.aliyun.com/repository/jcenter/' }
    maven { url 'https://maven.aliyun.com/repository/public/' }
    maven { url 'https://maven.aliyun.com/repository/google/' }

}

//sourceCompatibility = 17

compileKotlin {
    kotlinOptions.jvmTarget = "17"
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    implementation(gradleApi())
    implementation(localGroovy())
//    compileOnly("com.android.tools.build:gradle:3.2.0")
    implementation('com.squareup:javapoet:1.13.0')
    api("com.android.tools.build:gradle:8.13.0")
    implementation("commons-io:commons-io:2.11.0")
    implementation("commons-codec:commons-codec:1.15")
    implementation("org.javassist:javassist:3.28.0-GA")
    implementation "org.jetbrains.kotlin:kotlin-stdlib:2.1.0"
//    implementation "org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.0"
//    implementation(libs.plugin.kotlin)


}
sourceSets {
    main {
        groovy.srcDirs = ['src/main/groovy', '../okrouter-plugin/src/main/kotlin']
        resources.srcDirs = ['src/main/resources', '../okrouter-plugin/src/main/resources']
        java.srcDirs = ['src/main/java', '../okrouter-plugin/src/main/kotlin']
    }
}

group = 'com.anymore'
version = '0.0.3'

java {
    withSourcesJar()
    withJavadocJar()
}

tasks.named('sourcesJar') {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

def mavenUsername = findProperty("maven_username") ?: System.getenv("ALIYUN_USERNAME")
def mavenPassword = findProperty("maven_password") ?: System.getenv("ALIYUN_PASSWORD")
def releasesRepoUrl = findProperty("maven_release_url") ?: System.getenv("MAVEN_RELEASE_URL") ?: "https://packages.aliyun.com/maven/repository/2202395-release-jr0puW/"
def snapshotsRepoUrl = findProperty("maven_snapshot_url") ?: System.getenv("MAVEN_SNAPSHOT_URL") ?: "https://packages.aliyun.com/maven/repository/2202395-snapshot-3OoSzj/"

publishing {
    publications {
        maven(MavenPublication) {
            artifactId = 'okrouter-plugin'
            from components.java
        }
    }

    repositories {
        maven {
            name = "privateMaven"
            url = version.endsWith('SNAPSHOT') ? snapshotsRepoUrl : releasesRepoUrl
            credentials {
                username mavenUsername
                password mavenPassword
            }
        }
    }
}
